version: "3"

services:
  app:
    container_name: myproject_app
    build: ./app
    ports:
      - "3100:3100"
      - "9229:9229"
    volumes:
      - ./app:/opt/app/myproject-app/app
    command: yarn start 

  client:
    container_name: myproject_client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/opt/app/myproject-client/src
      - ./client/public:/opt/app/myproject-client/public
    links:
      - app
    command: yarn start
    tty: true