version: "3"

services:
  app:
    container_name: trendauto_app
    build: ./app
    ports:
      - "3100:3100"
    volumes:
      - ./app/src:/opt/app/trendauto-app/src
    command: yarn start 

  client:
    container_name: trendauto_client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/opt/app/trendauto-client/src
      - ./client/public:/opt/app/trendauto-client/public
    links:
      - app
    command: yarn start
    tty: true